#!/bin/sh

readonly CARGO_DENY_VERSION=0.20.2
readonly CARGO_PUBLIC_API_VERSION=0.52.0
readonly CARGO_FUZZ_VERSION=0.13.2
readonly PUBLIC_API_TOOLCHAIN=nightly-2026-05-23
readonly FUZZ_TOOLCHAIN=nightly-2026-05-23
readonly API_SNAPSHOT_VERSION=1
readonly SECURITY_MODEL_VERSION=1
readonly ENGINEERING_EVIDENCE_VERSION=1
readonly CRYPTO_INVENTORY_VERSION=1
readonly RELEASE_CHECKLIST_VERSION=1
